Regression practice 2.0
UW-CEG/two-stage-2 pull request #26
Opened 2021-06-23 00:18 UTC by Ganling6666

2021-06-28 23:35 UTC, cfcraig approved these changes
looks good, only one minor typo to be aware of for future Rmd files :-)

2021-06-28 23:35 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.Rmd
> +###I would like to create a model that could implement the random effects based on the TA sections
There should be a space between "###" and "I" in order for this to be interpreted by markdown as a header.

2021-06-29 01:40 UTC, Ganling6666 commented
I have changed the TA sections and they should now be unique!

2021-06-29 03:41 UTC, cfcraig requested changes
Please add spaces after # header designations so markdown will interpret them correctly, then recompile the MD files. 

Your addition of the vectorized code looks great. 👌

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.Rmd
> +####Again, the change of AIC is much bigger than 2
You have to leave a space after the #### tag for markdown to interpret this line as a header.

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.Rmd
> +#Include eop_id as a control variable
`eop_id` and other demographics variables aren't really controls in our work... they are groups designated by categorical variables that we care about in our models. We are trying to compare groups of interest (women, URMs, FGNs, EOPs) to their traditionally overserved counterparts. This is in contrast to the control variables which we want to include to make sure we compare students at the same "elevation"--- across all demo groups--- in terms of academic backgrounds, but we don't really care about the estimates that come out of the regression for the control variables. We do care about the outcomes for the groups of interest. We can discuss this more tomorrow.

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.md
> +###Import and read the data
Need space after ###

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.md
> +####Creating unique rows and remove the ones that are not necessary for this data model
Need space after ####

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.md
> +##Make 'ta_sect'unique across different data values
Need space after ##

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.md
> +####First, we need to split the data from into year 16 and year 17
Etc

2021-06-29 03:41 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_tables.md
> +####Use the vectorization function in R, we can add '_16' and '_17'at the end of each TA section
Etc

2021-07-06 08:19 UTC, closed without merging