Model selection
UW-CEG/two-stage-2 pull request #33
Opened 2021-07-20 21:58 UTC by Ganling6666

Trying to select the best fit model for each demographic identifier.

2021-08-03 21:08 UTC, cfcraig requested changes
Please add `summary(_dem__mod4)` for each demographic variable in the model selection section.

2021-08-03 21:08 UTC, cfcraig commented on processing-and-analysis/02-command-files/Ganling's file/Random_effect_Interaction.Rmd
> +```
Please add `summary(_dem__mod4)` for each demographic variable

2021-08-10 05:03 UTC, Ganling6666 commented
Made some changes. Now I have correct data-wrangling codes but the model selection part is not making sense.

2021-08-11 00:48 UTC, cfcraig requested changes
* Complete the model selection with correct dataset
* Update script according to [style guide](https://docs.google.com/document/d/1sycWoBUs5jPM83M2ywRJtv-EBo1t2rvR1wDhM7jS1W8/edit#heading=h.piug88d0vy62) introduced in 2021-08-10 meeting.

2021-08-17 06:49 UTC, Ganling6666 commented
The new file for model selection is called "random_effect_model_selection". I created a new file to make it look less messy

2021-08-18 01:07 UTC, cfcraig approved these changes
Good use of commits to structure your model selection...it was easy to follow your changes. Couple things I'd also like to see in the future:

* More descriptive commit messages, so I have a better sense of the purpose of the changes in each commit
* Commit messages that are formatted as an action, such as: "conduct model selection on `fgn` and `urm`" for your last commit.

2021-08-22 00:45 UTC, merged